import{a as h,S as M,i as c}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();h.defaults.baseURL="https://pixabay.com/api/";async function y(e,r=1){const i={key:"53595535-e5f82fa4261a3268ac261655e",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await h.get("/",{params:i})).data}catch(s){return console.error("Error fetching images:",s),null}}const g=document.querySelector(".gallery"),l=document.querySelector("[data-loader]"),u=document.getElementById("load-more"),P=new M(".gallery a");function p(e){const r=e.map(({webformatURL:i,largeImageURL:s,tags:t,likes:o,views:a,comments:w,downloads:B})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${i}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${a}</p>
          <p class="info-item"><b>Comments</b> ${w}</p>
          <p class="info-item"><b>Downloads</b> ${B}</p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",r),P.refresh()}function q(){g.innerHTML=""}function b(){l&&l.classList.remove("hidden")}function d(){l&&l.classList.add("hidden")}function E(){u&&u.classList.remove("hidden")}function f(){u&&u.classList.add("hidden")}function S(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}const $=document.querySelector(".form"),H=document.querySelector('input[name="search-text"]');let m="",n=1;const L=15;function v(e){const r=Math.ceil(e/L);n<r?E():f()}$.addEventListener("submit",async e=>{e.preventDefault();const r=H.value.trim();if(r){f(),m=r,n=1,q(),b();try{const i=await y(m,n);d(),i&&i.hits.length>0?(p(i.hits),v(i.totalHits)):c.error({title:"Sorry, there are no images matching your search query. Please try again!",timeout:4e3})}catch(i){d(),c.error({title:"Не вдалось завантажити зображення",message:i.message,timeout:4e3})}}});const O=document.getElementById("load-more");O.addEventListener("click",async()=>{n+=1,b();try{const e=await y(m,n);if(d(),e&&e.hits.length>0){p(e.hits),S(),v(e.totalHits);const r=Math.ceil(e.totalHits/L);n>=r&&(f(),c.info({title:"We're sorry, but you've reached the end of search results.",timeout:4e3}))}else f(),c.info({title:"We're sorry, but you've reached the end of search results.",timeout:4e3})}catch(e){d(),c.error({title:"Не вдалось завантажити зображення",message:e.message,timeout:4e3})}});
//# sourceMappingURL=index.js.map
