import{a as h,S as M,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(t){if(t.ep)return;t.ep=!0;const i=r(t);fetch(t.href,i)}})();h.defaults.baseURL="https://pixabay.com/api/";async function y(e,o=1){const r={key:"53595535-e5f82fa4261a3268ac261655e",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await h.get("/",{params:r})).data}catch(s){return console.error("Error fetching images:",s),null}}const g=document.querySelector(".gallery"),u=document.querySelector("[data-loader]"),d=document.getElementById("load-more"),q=new M(".gallery a");function p(e){const o=e.map(({webformatURL:r,largeImageURL:s,tags:t,likes:i,views:c,comments:w,downloads:P})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${r}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${i}</p>
          <p class="info-item"><b>Views</b> ${c}</p>
          <p class="info-item"><b>Comments</b> ${w}</p>
          <p class="info-item"><b>Downloads</b> ${P}</p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",o),q.refresh()}function B(){g.innerHTML=""}function b(){u&&u.classList.remove("hidden")}function L(){u&&u.classList.add("hidden")}function E(){d&&d.classList.remove("hidden")}function a(){d&&d.classList.add("hidden")}function S(){requestAnimationFrame(()=>{const e=document.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}})}const $=document.querySelector(".form"),H=document.querySelector('input[name="search-text"]');let f="",l=1;const m=15;function v(e){const o=Math.ceil(e/m);l<o?E():a()}$.addEventListener("submit",async e=>{e.preventDefault();const o=H.value.trim();if(!o){n.warning({title:"Ввдіть пошуковий запит",timeout:3e3});return}a(),f=o,l=1,B(),b();try{const r=await y(f,l);r&&r.hits.length>0?(p(r.hits),v(r.totalHits),Math.ceil(r.totalHits/m)<=1&&(a(),n.info({title:"You've reached the end of search results.",timeout:3e3}))):n.error({title:"Sorry, there are no images matching your search query. Please try again!",timeout:4e3})}catch(r){n.error({title:"Не вдалось завантажити зображення",message:r.message,timeout:4e3})}finally{L()}});const O=document.getElementById("load-more");O.addEventListener("click",async()=>{a(),l+=1,b();try{const e=await y(f,l);if(e&&e.hits.length>0){p(e.hits),S(),v(e.totalHits);const o=Math.ceil(e.totalHits/m);l>=o&&(a(),n.info({title:"We're sorry, but you've reached the end of search results.",timeout:4e3}))}else a(),n.info({title:"We're sorry, but you've reached the end of search results.",timeout:4e3})}catch(e){n.error({title:"Не вдалось завантажити зображення",message:e.message,timeout:4e3})}finally{L()}});
//# sourceMappingURL=index.js.map
